import HelperLayout from '@/components/layout/HelperLayout';
import Head from 'next/head'
import Link from 'next/link';
const navItems = [
  {
    name: "Credit Card Validation",
    link: "/card-validation",
  },
  {
    name: "Hamming Code",
    link: "/hamming-code",
  },
  {
    name: "Brute Force Password Cracking",
    link: "/brute-force-password",
  },
  {
    name: "Steganography",
    link: "/steganography",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HelperLayout>
        <div className="flex justify-center">
          <div className="grid grid-cols-2 gap-4">
            {navItems.map(item => (
              <Link
                href={item.link}
                key={item.link}
                  className="font-medium ring-1 ring-gray-100 rounded-lg px-10 py-5 text-center shadow-lg hover:shadow-neutral-100 transition-shadow"
              >
                {item.name}
              </Link>
            ))}
          </div>
        </div>
      </HelperLayout>
    </>
  );
}
